### ISSUE TITLE
Why offer string_tree as it contains pointers?

### ISSUE THREAD

**Issue by kjelle** [kentik/patricia#8]
Hello.
Just curious, why offer a string_tree when it contains pointers and creates high GC pressure?
Thanks.

**Comment by wblakecaldwell** [comment]
@kjelle - Sorry for the super late reply. 

If you need to map IPs to strings, I'm not sure if it's better to use an `int` tree, and put the strings in a `map[int]string`, or use a string tree. I'd have to try it out. Thoughts?
